[package]
name = "zellij-datetime"
version = "0.1.3"
authors = ["h1romas4 <h1romas4@gmail.com>"]
edition = "2021"

[dependencies]
zellij-tile = "^0.36.0"
zellij-tile-utils = "0.36.0"
ansi_term = "0.12"
chrono-wasi = "0.4.11"
