[package]
name = "zellij-datetime"
version = "0.6.1"
authors = ["h1romas4 <h1romas4@gmail.com>"]
edition = "2021"

[dependencies]
zellij-tile = "0.37.1"
zellij-tile-utils = "0.37.1"
ansi_term = "^0.12"
chrono-wasi = "^0.4"
