name: Release

on:
  push:
    tags:
      - '*'

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/wasm32-wasi/release/zellij-datetime.wasm"
        token: ${{ secrets.GITHUB_TOKEN }}
